--- 
- hosts: 172.31.46.107
  become: yes 
  tasks: 
  - include_tasks: myfile.yml 
  - name: install webserver
    apt: 
      name: apache2 
      state: present 
  - name: copy my test file into node side 
    copy: 
      src: mytestfile 
      dest: /home/ubuntu 

  - name: download files from internet 
    get_url: 
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes 

  - name: copy dyno file into node side 
    template: 
       src: myindexfile.j2
       dest: /var/www/html/index.html   